"""Shared utility functions for data loading and processing."""

from .data_utils import (
    load_embeddings_as_dict,
    load_movie_embeddings,
    load_movie_data,
    load_final_dataset,
    load_final_dense_embeddings,
    load_final_sparse_embeddings,
    load_final_data_with_embeddings,
    load_final_data_limited,
    preprocess_genres,
    cluster_genres,
    search_movies_by_keywords,
    expand_by_genre,
    map_genre_ids_to_strings,
    keep_top_n_genres,
    keep_selected_top_genres,
    keep_x_top_genres,
    drop_nan_in_column,
    filter_movies_with_given_genre,
)

__all__ = [
    "load_embeddings_as_dict",
    "load_movie_embeddings",
    "load_movie_data",
    "load_final_dataset",
    "load_final_dense_embeddings",
    "load_final_sparse_embeddings",
    "load_final_data_with_embeddings",
    "load_final_data_limited",
    "preprocess_genres",
    "cluster_genres",
    "search_movies_by_keywords",
    "expand_by_genre",
    "map_genre_ids_to_strings",
    "keep_top_n_genres",
    "keep_selected_top_genres",
    "keep_x_top_genres",
    "drop_nan_in_column",
    "filter_movies_with_given_genre",
]
